### ISSUE TITLE
String length defines

### ISSUE THREAD

**Issue by DizzyEggg** [pret/pokeemerald#132]
#define BERRY_NAME_COUNT 7 - 6 chars and EOS
#define PLAYER_NAME_LENGTH  8 - 7 chars and EOS
#define POKEMON_NAME_LENGTH 10 - 10 chars and EOS
#define OT_NAME_LENGTH 7 - 7 chars and EOS

As you can see PLAYER_NAME_LENGTH and BERRY_NAME_COUNT are different in that they add EOS to the length. We should agree whether string length defines consider EOS.

**Comment by Diegoisawesome** [comment]
If I'm not mistaken, the player's name can only be a max of 7 chars but takes up 8 with its EOS, but the POKEMON_NAME_LENGTH can be a max of 10 chars, foregoing the EOS entirely with a hardcoded maximum length. The defines are weird because the game is weird, but you're right that they should be standardized somehow.

**Comment by camthesaxman** [comment]
I suggest if the string uses EOS, which is the common case, define the length not including the EOS, and then add one to the buffer size.
```
#define EXAMPLE_NAME_LENGTH 10
u8 exampleName[EXAMPLE_NAME_LENGTH + 1];  // 11 bytes in size
```
If it's not terminated with EOS, then just don't add the +1
```
#define EXAMPLE_NAME_LENGTH 10
u8 exampleName[EXAMPLE_NAME_LENGTH];  // 10 bytes in size
```

**Comment by Diegoisawesome** [comment]
So can this be closed?

**Comment by DizzyEggg** [comment]
It didn't get resolved, the issue is still there
