### ISSUE TITLE
Issues pulling from ghoulslash fork

### ISSUE THREAD

**Issue by AlternisDim20** [pret/pokeemerald#1551]
Firstly, ghoulslash's auto_run feature isn't available; trying to run "git pull ghoul auto_run" just results in "fatal: couldn't find remote ref auto_run".

Secondly, trying to "git pull ghoul bag_sort" gives 

```
remote: Enumerating objects: 46, done.
remote: Counting objects: 100% (44/44), done.
remote: Compressing objects: 100% (12/12), done.
remote: Total 32 (delta 26), reused 26 (delta 20), pack-reused 0
Unpacking objects: 100% (32/32), 18.37 KiB | 254.00 KiB/s, done.
From https://github.com/ghoulslash/pokeemerald
 * branch                bag_sort   -> FETCH_HEAD
 * [new branch]          bag_sort   -> ghoul/bag_sort
Auto-merging src/item_menu.c
CONFLICT (content): Merge conflict in src/item_menu.c
Auto-merging include/item_menu.h
CONFLICT (content): Merge conflict in include/item_menu.h
Auto-merging include/item.h
Automatic merge failed; fix conflicts and then commit the result.
```

Which I don't know how to resolve...do I delete the src/item_menu.c and include/item_menu.h and include/item.h files I already have?

**Comment by GriffinRichards** [comment]
This is pret/pokeemerald, not ghoulslash's fork of pokeemerald. If you have an issue with a specific fork of pokeemerald please open an issue on that fork, not here.
If you need specific help you're better off asking on Discord or whatever thread you got this information from, rather than in a GitHub issue.
