### ISSUE TITLE
map filestructure

### ISSUE THREAD

**Issue by yenatch** [pret/pokeemerald#2]
```
- data/
 - maps/
  - _attributes.s
  - _connections.s
  - _events.s
  - _groups.s
  - _headers.s
  - _scripts.s
  - PetalburgCity/
   - attributes.s
   - border.bin
   - connections.s
   - events.s
   - header.s
   - map.bin
   - scripts.s
 - tilesets/
  - _assets.s
  - _headers.s
  - city/
   - animations.bin
   - blocks.bin
   - image.4bpp.lz
   - palettes.bin
```

**Comment by YamaArashi** [comment]
I have already dumped the tileset data, except the metatile (block) data is still incbins instead of .bin files. https://github.com/pret/pokeemerald/tree/master/data/graphics/tilesets

I agree with the file structure for maps, except I am not sure about the "attributes" name because it is a bit vague. I was thinking it could be called "layout" or something similar similar because it contains data about the map grid itself.
