### ISSUE TITLE
Compiling-problems

### ISSUE THREAD

**Issue by JaceCearK1** [pret/pokeemerald#3]
I've tried compiling/assembling pokeemerald by using devkitpro/GCC but it looks like the .charmap, .charmapconst and .charmapstr Pseudo-Ops used for RSE's custom character-mapping are not compatible with the stock-assembler/compiler!
Could you provide installing instructions or a link to the compiler-binary that you use in the readme file? Would be much appreciated!

**Comment by JaceCearK1** [comment]
@YamaArashi sorry to bother you, but you seem to know the answer to my problems stated above since you are/were very active in this repo!
Thanks in advance for any kind of help or advice you can provide! :)

**Comment by YamaArashi** [comment]
Currently these projects need to be compiled in order to build it, but configuring them is a bit of a mess.
https://github.com/YamaArashi/gbacc
https://github.com/YamaArashi/pokebinutils

I am working on an integrated solution that will compile with just "make", but I am not sure how long it will take me to release it. I could release a zip file containing Windows exe files that can build it for now if you'd like that.

**Comment by JaceCearK1** [comment]
That would be nice!
I worked on a disassembly for Emerald aswell, which to be honest is a real mess and doesn't come close to booting up (it **does** compile though ^^), but maybe I can contribute with one thing or another in the future! :)

**Comment by camthesaxman** [comment]
You should probably put that information in the README.md file.

Yeah, gcc and binutils are always a pain in the butt to compile. Their build system is broken beyond belief. I started an Emerald disassembly two years ago using FASMARM as my assembler, but seeing that this project is so much further along, I gave it up. With FASM's incredibly powerful preprocessor, I was able to define a macro that took a string literal, read the characters, and replaced them with the corresponding bytes from the custom character encoding, which made it very easy to input text in the game. You might want to see if DevKitPro's GAS has any similar capabilities.

**Comment by YamaArashi** [comment]
Yes. I will put that in the README.md.

I am pretty sure that gas does not have similar capabilities with respect to its macros. I am currently in the process of rewriting much of gas in an attempt to improve its assembly speed and simplify its code. I think it can be made a lot faster.

With regard to this disassembly, I am currently focusing more on Ruby due to it being simpler in general. https://github.com/pret/pokeruby I am also attempting to decompile it into C code that compiles back to the original ROM. I have encountered a lot more problems getting the compiler's output to match the ROM with Emerald than with Ruby, though there are cases where inline assembly must be used in Ruby as well, at least for now.

**Comment by JaceCearK1** [comment]
So, uhh...
Did you upload the compiler binaries anywhere @YamaArashi? ^^

**Comment by YamaArashi** [comment]
I have put instructions for compiling at https://github.com/pret/pokeruby. I am not sure when I will be able to convert pokeemerald to build using this system.

**Comment by JaceCearK1** [comment]
Thank you! :)

**Comment by camthesaxman** [comment]
@YamaArashi You said that you had a lot more problems getting the compiler output to match. Ruby was released in 2002 in Japan, and Emerald was released in 2004, so is it possible that Emerald was built with a newer version of the SDK than Ruby? I'm sure the vast majority of code is the same between the two and we should be able to import a lot of Ruby's code here once Ruby gets further along.

**Comment by YamaArashi** [comment]
I have wondered if that's the case, but I don't think it is. I have a copy of the latest version of the compiler (later than the one used for Ruby), as far as I know, but it doesn't seem any easier with that one. So I think it could be due to the coding style in Emerald, but I am not sure.

**Comment by shinyquagsire23** [comment]
Even between Ruby and Fire Red it's extremely apparently they did a compiler change/update. In my own reversing I've found interesting compiler differences between identical functions, and the Fire Red compiler seems to do several things in a more-optimized fashion.

**Comment by YamaArashi** [comment]
Really? I'll have to take another look. Do you know any particular functions?

**Comment by shinyquagsire23** [comment]
I'll have to search around a bit, it's not that common but in some functions you can tell. Same thing with Emerald vs Fire Red, there's tiny compiler differences in places.

**Comment by YamaArashi** [comment]
Well, I will look into this more when Ruby is further along and integrating the code from there into this repo makes sense.

**Comment by YamaArashi** [comment]
This issue has been resolved.
