### ISSUE TITLE
Milestone: Phase out devkitARM

### ISSUE THREAD

**Issue by PikalaxALT** [pret/pokeemerald#663]
devkitARM has been the bane of many of our existences, and it's time we move away from it.  To do this, we will need to supply our own C preprocessor (consistent with the C99 standard plus the current functionality of preproc) and ARMv4t assembler.  @easyaspi314 has been working on developing this independent toolchain, and I think it's worth tracking progress on this in a dedicated thread.

**Comment by easyaspi314** [comment]
Once midterms are finished I will try and contribute some more. However, it is almost complete and mostly in the bugfixing stage.

Summary of the work I was doing:
 - Lean, mean, ARMv4t machine binutils which has most of the unrelated code trimmed, bringing the previously 240 MB source tree to 9.5 MB. This supplies `ar`, `as`, `ld`, `objcopy`, `objdump`, and `ranlib` only, and they are tuned specifically for ARMv4t.
 - ucpp-based C99 preprocessor which has builtin preproc support:
   - On C files, it preprocesses source and uses the pragma hook feature to parse incbins on-the-fly instead of parsing the file twice.
   - This removes the man-in-the-middle approach.
- GCC has been modified to have better C99 support (unfortunately no mixed declarations yet/ever). It now supports restrict, bool, inttypes.h, stdbool.h, inline (although semantics are not the same), and up to date limits.h.
- GCC now has better warnings.
   - Just like modern GCC, it will colorize the output to stand out from the build log
   - It also shows the affected line.
   - While the warnings are still pretty lame, the verbosity has been increased so at least you get more information
- GCC now properly aligns the .text section after compiling, so the printf step in the build system is removed.
   - This also allows us to pipe everything directly, reducing the number of build files. This is togglable, if I properly implemented it. 
- scaninc has been improved in that it caches results to files which make parses. This makes incremental builds much faster and decreases the memory usage on builds.
- On pokeruby, makefiles use a fancier output. This is soon to be ported to pokeemerald once midterms are over.

**Comment by PikalaxALT** [comment]
Closing this issue as unresolved, since the work on pret/agbcc towards this goal has long since been abandoned.
